CREATE TABLE IF NOT EXISTS facilities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  unit TEXT NOT NULL DEFAULT 'sq ft'
);

CREATE TABLE IF NOT EXISTS zones (
  id TEXT PRIMARY KEY,
  facility_id INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  zone_type TEXT NOT NULL CHECK (zone_type IN ('warehouse', 'workstation', 'dock', 'support')),
  process_order INTEGER,
  area_sq_ft INTEGER NOT NULL,
  primary_flow TEXT NOT NULL,
  status TEXT NOT NULL,
  description TEXT NOT NULL,
  map_x INTEGER NOT NULL,
  map_y INTEGER NOT NULL,
  map_width INTEGER NOT NULL,
  map_height INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS materials (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  material_type TEXT NOT NULL CHECK (material_type IN ('raw', 'wip', 'finished')),
  default_zone_id TEXT NOT NULL REFERENCES zones(id)
);

CREATE TABLE IF NOT EXISTS process_steps (
  id TEXT PRIMARY KEY,
  facility_id INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
  step_number INTEGER NOT NULL,
  source_zone_id TEXT NOT NULL REFERENCES zones(id),
  target_zone_id TEXT NOT NULL REFERENCES zones(id),
  name TEXT NOT NULL,
  expected_minutes INTEGER NOT NULL,
  route_type TEXT NOT NULL CHECK (route_type IN ('material', 'return', 'rework'))
);

CREATE TABLE IF NOT EXISTS inventory_balances (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_id INTEGER NOT NULL REFERENCES materials(id),
  zone_id TEXT NOT NULL REFERENCES zones(id),
  quantity_on_hand INTEGER NOT NULL DEFAULT 0,
  reorder_point INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (material_id, zone_id)
);

CREATE TABLE IF NOT EXISTS inventory_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area TEXT NOT NULL CHECK (area IN ('Parts', 'Production', 'Finished Goods')),
  location_zone_id TEXT NOT NULL REFERENCES zones(id),
  item_name TEXT NOT NULL,
  part_number TEXT NOT NULL,
  quantity_on_hand NUMERIC(12, 3) NOT NULL DEFAULT 0,
  quantity_allocated NUMERIC(12, 3) NOT NULL DEFAULT 0,
  quantity_available NUMERIC(12, 3) GENERATED ALWAYS AS (quantity_on_hand - quantity_allocated) STORED,
  unit TEXT NOT NULL,
  min_quantity NUMERIC(12, 3) NOT NULL DEFAULT 0,
  max_quantity NUMERIC(12, 3) NOT NULL DEFAULT 0,
  status TEXT NOT NULL CHECK (status IN ('Ready', 'Watch', 'Reorder', 'In process', 'Open capacity', 'Clear')),
  control_note TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (area, location_zone_id, part_number)
);

CREATE TABLE IF NOT EXISTS work_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_order_no TEXT NOT NULL UNIQUE,
  material_id INTEGER NOT NULL REFERENCES materials(id),
  current_zone_id TEXT NOT NULL REFERENCES zones(id),
  quantity INTEGER NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('planned', 'in_progress', 'hold', 'complete')),
  due_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS production_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no TEXT NOT NULL UNIQUE,
  finished_material_id INTEGER NOT NULL REFERENCES materials(id),
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  status TEXT NOT NULL CHECK (status IN ('planned', 'released', 'in_progress', 'hold', 'complete', 'cancelled')),
  current_zone_id TEXT NOT NULL REFERENCES zones(id),
  start_date DATE NOT NULL,
  due_date DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bom_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_material_id INTEGER NOT NULL REFERENCES materials(id),
  part_number TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  quantity NUMERIC(12, 3) NOT NULL,
  unit TEXT NOT NULL,
  station_zone_id TEXT REFERENCES zones(id),
  supply_type TEXT NOT NULL CHECK (supply_type IN ('make', 'buy')),
  notes TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS production_order_materials (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id INTEGER NOT NULL REFERENCES production_orders(id) ON DELETE CASCADE,
  bom_item_id INTEGER REFERENCES bom_items(id),
  part_number TEXT NOT NULL,
  description TEXT NOT NULL,
  required_quantity NUMERIC(12, 3) NOT NULL,
  issued_quantity NUMERIC(12, 3) NOT NULL DEFAULT 0,
  consumed_quantity NUMERIC(12, 3) NOT NULL DEFAULT 0,
  unit TEXT NOT NULL,
  source_zone_id TEXT NOT NULL REFERENCES zones(id),
  status TEXT NOT NULL CHECK (status IN ('planned', 'allocated', 'issued', 'consumed', 'short')),
  UNIQUE (production_order_id, part_number)
);

CREATE TABLE IF NOT EXISTS production_order_operations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id INTEGER NOT NULL REFERENCES production_orders(id) ON DELETE CASCADE,
  process_step_id TEXT REFERENCES process_steps(id),
  sequence_number INTEGER NOT NULL,
  zone_id TEXT NOT NULL REFERENCES zones(id),
  operation_name TEXT NOT NULL,
  planned_minutes INTEGER NOT NULL,
  actual_minutes INTEGER NOT NULL DEFAULT 0,
  quantity_in INTEGER NOT NULL DEFAULT 0,
  quantity_out INTEGER NOT NULL DEFAULT 0,
  scrap_quantity INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL CHECK (status IN ('queued', 'ready', 'in_progress', 'complete', 'hold')),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  UNIQUE (production_order_id, sequence_number)
);

CREATE TABLE IF NOT EXISTS workstation_balances (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id INTEGER NOT NULL REFERENCES production_orders(id) ON DELETE CASCADE,
  zone_id TEXT NOT NULL REFERENCES zones(id),
  wip_quantity INTEGER NOT NULL DEFAULT 0,
  completed_quantity INTEGER NOT NULL DEFAULT 0,
  hold_quantity INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (production_order_id, zone_id)
);

CREATE TABLE IF NOT EXISTS production_order_activity (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id INTEGER NOT NULL REFERENCES production_orders(id) ON DELETE CASCADE,
  operation_id INTEGER REFERENCES production_order_operations(id) ON DELETE SET NULL,
  activity_type TEXT NOT NULL CHECK (activity_type IN ('created', 'released', 'material_issued', 'started', 'moved', 'completed', 'held', 'reworked', 'adjusted')),
  from_zone_id TEXT REFERENCES zones(id),
  to_zone_id TEXT REFERENCES zones(id),
  quantity INTEGER NOT NULL DEFAULT 0,
  notes TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS inventory_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id INTEGER REFERENCES production_orders(id) ON DELETE SET NULL,
  inventory_item_id INTEGER REFERENCES inventory_items(id) ON DELETE SET NULL,
  transaction_type TEXT NOT NULL CHECK (transaction_type IN ('create', 'allocate', 'issue', 'consume', 'move', 'complete', 'adjust', 'rework')),
  from_zone_id TEXT REFERENCES zones(id),
  to_zone_id TEXT REFERENCES zones(id),
  part_number TEXT NOT NULL,
  quantity NUMERIC(12, 3) NOT NULL,
  unit TEXT NOT NULL,
  reference TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS production_workstation_ledger (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_id INTEGER NOT NULL REFERENCES production_orders(id) ON DELETE CASCADE,
  zone_id TEXT NOT NULL REFERENCES zones(id),
  transaction_type TEXT NOT NULL CHECK (transaction_type IN ('in', 'out', 'adjustment', 'hold', 'scrap')),
  quantity_in NUMERIC(12, 3) NOT NULL DEFAULT 0,
  quantity_out NUMERIC(12, 3) NOT NULL DEFAULT 0,
  adjustment_quantity NUMERIC(12, 3) NOT NULL DEFAULT 0,
  balance_after NUMERIC(12, 3) NOT NULL DEFAULT 0,
  accounting_event TEXT NOT NULL,
  reference TEXT NOT NULL,
  notes TEXT NOT NULL,
  transaction_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (production_order_id, zone_id, transaction_type, reference)
);

CREATE INDEX IF NOT EXISTS idx_zones_facility_order ON zones(facility_id, process_order);
CREATE INDEX IF NOT EXISTS idx_process_steps_order ON process_steps(facility_id, step_number);
CREATE INDEX IF NOT EXISTS idx_inventory_zone ON inventory_balances(zone_id);
CREATE INDEX IF NOT EXISTS idx_inventory_items_area ON inventory_items(area);
CREATE INDEX IF NOT EXISTS idx_inventory_items_location ON inventory_items(location_zone_id);
CREATE INDEX IF NOT EXISTS idx_inventory_items_status ON inventory_items(status);
CREATE INDEX IF NOT EXISTS idx_work_orders_status ON work_orders(status);
CREATE INDEX IF NOT EXISTS idx_bom_items_parent ON bom_items(parent_material_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_production_orders_order_no_unique ON production_orders(order_no);
CREATE INDEX IF NOT EXISTS idx_production_orders_status ON production_orders(status);
CREATE INDEX IF NOT EXISTS idx_production_order_operations_order ON production_order_operations(production_order_id, sequence_number);
CREATE INDEX IF NOT EXISTS idx_workstation_balances_order ON workstation_balances(production_order_id);
CREATE INDEX IF NOT EXISTS idx_production_order_activity_order ON production_order_activity(production_order_id, created_at);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_order ON inventory_transactions(production_order_id, created_at);
CREATE INDEX IF NOT EXISTS idx_workstation_ledger_order ON production_workstation_ledger(production_order_id, transaction_at);
CREATE INDEX IF NOT EXISTS idx_workstation_ledger_zone ON production_workstation_ledger(zone_id, transaction_type);

CREATE OR REPLACE FUNCTION next_production_order_no()
RETURNS TEXT
LANGUAGE sql
AS $$
  SELECT 'DRN-PO-' || lpad(
    (
      COALESCE(
        MAX(NULLIF(regexp_replace(order_no, '^DRN-PO-', ''), '')::INTEGER),
        1000
      ) + 1
    )::TEXT,
    4,
    '0'
  )
  FROM production_orders
  WHERE order_no ~ '^DRN-PO-[0-9]+$';
$$;

CREATE OR REPLACE FUNCTION create_production_order(
  p_order_no TEXT,
  p_quantity INTEGER,
  p_due_date DATE,
  p_start_date DATE DEFAULT CURRENT_DATE
)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_order_id INTEGER;
  v_finished_material_id INTEGER;
BEGIN
  IF p_quantity <= 0 THEN
    RAISE EXCEPTION 'Production order quantity must be greater than zero';
  END IF;

  SELECT id
  INTO v_finished_material_id
  FROM materials
  WHERE sku = 'DRN-FG-600';

  IF v_finished_material_id IS NULL THEN
    RAISE EXCEPTION 'Finished material DRN-FG-600 is missing';
  END IF;

  INSERT INTO production_orders (
    order_no, finished_material_id, quantity, status,
    current_zone_id, start_date, due_date
  )
  VALUES (
    p_order_no, v_finished_material_id, p_quantity, 'planned',
    'receiving', p_start_date, p_due_date
  )
  RETURNING id INTO v_order_id;

  INSERT INTO production_order_materials (
    production_order_id, bom_item_id, part_number, description,
    required_quantity, unit, source_zone_id, status
  )
  SELECT
    v_order_id,
    bi.id,
    bi.part_number,
    bi.description,
    bi.quantity * p_quantity,
    bi.unit,
    COALESCE(bi.station_zone_id, 'raw'),
    CASE WHEN bi.supply_type = 'buy' THEN 'allocated' ELSE 'planned' END
  FROM bom_items bi
  WHERE bi.parent_material_id = v_finished_material_id
    AND bi.part_number <> 'DRN-FG-600'
  ORDER BY bi.id;

  INSERT INTO production_order_operations (
    production_order_id, process_step_id, sequence_number, zone_id,
    operation_name, planned_minutes, quantity_in, status
  )
  SELECT
    v_order_id,
    ps.id,
    ps.step_number,
    ps.target_zone_id,
    ps.name,
    ps.expected_minutes,
    CASE WHEN ps.step_number = 1 THEN p_quantity ELSE 0 END,
    CASE WHEN ps.step_number = 1 THEN 'ready' ELSE 'queued' END
  FROM process_steps ps
  WHERE ps.facility_id = 1
  ORDER BY ps.step_number;

  INSERT INTO workstation_balances (
    production_order_id, zone_id, wip_quantity, completed_quantity, hold_quantity
  )
  SELECT
    v_order_id,
    z.id,
    CASE WHEN z.id = 'receiving' THEN p_quantity ELSE 0 END,
    0,
    0
  FROM zones z
  WHERE z.id IN ('receiving', 'raw', 'ws1', 'ws2', 'ws3', 'ws4', 'ws5', 'fg', 'inventory')
  ORDER BY z.process_order;

  INSERT INTO production_order_activity (
    production_order_id, activity_type, to_zone_id, quantity, notes
  )
  VALUES (
    v_order_id, 'created', 'receiving', p_quantity,
    'Production order created at Receiving for testing before raw material release to finished goods route.'
  );

  INSERT INTO inventory_transactions (
    production_order_id, transaction_type, to_zone_id, part_number,
    quantity, unit, reference
  )
  VALUES (
    v_order_id, 'create', 'receiving', 'DRN-FG-600',
    p_quantity, 'each', p_order_no
  );

  INSERT INTO production_workstation_ledger (
    production_order_id, zone_id, transaction_type, quantity_in,
    balance_after, accounting_event, reference, notes
  )
  VALUES (
    v_order_id, 'receiving', 'in', p_quantity,
    p_quantity, 'WIP_RECEIPT', p_order_no || '-receiving-in',
    'Initial production order quantity received into Receiving WIP.'
  );

  RETURN v_order_id;
END;
$$;
