-- 009: Purchasing module — vendors, sourcing catalog with price breaks,
-- EOQ policy settings, vendor purchase orders, and the 2000 Accounts
-- Payable account. Idempotent; the same statements live in schema.sql,
-- so running the full schema also applies this migration.

CREATE TABLE IF NOT EXISTS vendors (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  contact TEXT NOT NULL DEFAULT '',
  terms TEXT NOT NULL DEFAULT 'Net 30',
  lead_time_days INTEGER NOT NULL DEFAULT 7 CHECK (lead_time_days >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vendor_parts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id INTEGER NOT NULL REFERENCES vendors(id) ON DELETE CASCADE,
  part_number TEXT NOT NULL,
  vendor_model TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
  moq INTEGER NOT NULL DEFAULT 1 CHECK (moq >= 1),
  lead_time_days INTEGER,
  availability TEXT NOT NULL DEFAULT 'In stock',
  preferred BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE (vendor_id, part_number)
);
CREATE INDEX IF NOT EXISTS idx_vendor_parts_part ON vendor_parts(part_number);

CREATE TABLE IF NOT EXISTS vendor_price_breaks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_part_id INTEGER NOT NULL REFERENCES vendor_parts(id) ON DELETE CASCADE,
  min_qty INTEGER NOT NULL CHECK (min_qty > 1),
  unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
  UNIQUE (vendor_part_id, min_qty)
);

CREATE TABLE IF NOT EXISTS purchasing_settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  ordering_cost NUMERIC(10, 2) NOT NULL DEFAULT 25.00 CHECK (ordering_cost > 0),
  carrying_rate_pct NUMERIC(6, 2) NOT NULL DEFAULT 25.00 CHECK (carrying_rate_pct > 0),
  safety_stock_days INTEGER NOT NULL DEFAULT 5 CHECK (safety_stock_days >= 0),
  planned_annual_builds INTEGER NOT NULL DEFAULT 250 CHECK (planned_annual_builds > 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO purchasing_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS purchase_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_no TEXT NOT NULL UNIQUE,
  vendor_id INTEGER NOT NULL REFERENCES vendors(id),
  status TEXT NOT NULL DEFAULT 'issued' CHECK (status IN ('issued', 'received')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  received_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS purchase_order_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_order_id INTEGER NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
  part_number TEXT NOT NULL,
  vendor_model TEXT NOT NULL DEFAULT '',
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0)
);

INSERT INTO gl_accounts (account_no, name, account_type, normal_side) VALUES
  ('2000', 'Accounts Payable', 'liability', 'credit')
ON CONFLICT (account_no) DO NOTHING;

-- Vendor/catalog seed data lives in schema.sql (street-price research,
-- July 2026); apply the full schema to load it.
