-- 010: Email order intake — inbound_emails table, sales order draft /
-- backorder / rejected lifecycle, and the email link column. Idempotent;
-- the same statements live in schema.sql.

CREATE TABLE IF NOT EXISTS inbound_emails (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id TEXT UNIQUE,
  from_name TEXT NOT NULL DEFAULT '',
  from_email TEXT NOT NULL DEFAULT '',
  subject TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL DEFAULT '',
  received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'order_drafted', 'not_order', 'rejected', 'error')),
  classification TEXT,
  sales_order_id INTEGER REFERENCES sales_orders(id) ON DELETE SET NULL,
  processed_at TIMESTAMPTZ
);

ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS source_email_id INTEGER;
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMPTZ;
ALTER TABLE sales_orders DROP CONSTRAINT IF EXISTS sales_orders_status_check;
ALTER TABLE sales_orders ADD CONSTRAINT sales_orders_status_check
  CHECK (status IN ('draft', 'open', 'backorder', 'invoiced', 'cancelled', 'rejected'));
